"""empty message

Revision ID: 1b19f67f0e3f
Revises: 6ce3d6cfa7fd
Create Date: 2019-09-30 13:43:39.821198

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b19f67f0e3f'
down_revision = '6ce3d6cfa7fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('city_rubbish',
    sa.Column('rubbish_type_id', sa.Integer(), nullable=True),
    sa.Column('city_code_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['city_code_id'], ['py_city_code.id'], ),
    sa.ForeignKeyConstraint(['rubbish_type_id'], ['py_rubbish_type.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('city_rubbish')
    # ### end Alembic commands ###
