"""empty message

Revision ID: a61d55befad5
Revises: 1b19f67f0e3f
Create Date: 2019-09-30 13:50:24.696403

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a61d55befad5'
down_revision = '1b19f67f0e3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('py_rubbish_type', sa.Column('rubbish_term', sa.String(length=128), nullable=False))
    op.create_unique_constraint(None, 'py_rubbish_type', ['rubbish_term'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'py_rubbish_type', type_='unique')
    op.drop_column('py_rubbish_type', 'rubbish_term')
    # ### end Alembic commands ###
